# Generated by Django 4.2 on 2024-11-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='dish',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='dish',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='dish',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
    ]
